Vagrant.configure("2") do |config|
  # node-exp
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "bento/ubuntu-22.04"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", ip: "192.168.50.10"
    ubuntu1.vm.provision :shell, path: "node-exp.sh"
  end

  # prometheus
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "bento/ubuntu-22.04"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.network "private_network", ip: "192.168.50.11"
    ubuntu2.vm.provision :shell, path: "prometheus.sh"
  end
end
