Vagrant.configure("2") do |config|
  # # Node exporter
  # config.vm.define "node1" do |node1|
  #   node1.vm.box = "bento/ubuntu-22.04"
  #   node1.vm.hostname = "node1"
  #   node1.vm.network "private_network", ip: "192.168.50.10"
  #   node1.vm.provision "shell", inline: <<-SHELL
  #     cd /vagrant
  #     sudo bash node-exp.sh
  #     sudo bash tailscale.sh
  #   SHELL
  # end

  # Prometheus
  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.box = "bento/ubuntu-22.04"
    prometheus.vm.hostname = "prometheus"
    prometheus.vm.network "private_network", ip: "192.168.50.11"
    # prometheus.vm.provision "shell", inline: <<-SHELL
    #   cd /vagrant
    #   sudo bash prometheus.sh
    #   sudo bash tailscale.sh
    # SHELL
  end

  # # Grafana
  # config.vm.define "grafana" do |grafana|
  #   grafana.vm.box = "bento/ubuntu-22.04"
  #   grafana.vm.hostname = "grafana"
  #   grafana.vm.network "private_network", ip: "192.168.50.12"
  #   grafana.vm.provision "shell", inline: <<-SHELL
  #     cd /vagrant
  #     sudo bash grafana.sh
  #     sudo bash tailscale.sh
  #   SHELL
  # end
end
